(cl:defpackage localization_msgs-srv
  (:use )
  (:export
   "GETLANDMARKS"
   "<GETLANDMARKS-REQUEST>"
   "GETLANDMARKS-REQUEST"
   "<GETLANDMARKS-RESPONSE>"
   "GETLANDMARKS-RESPONSE"
   "GETSUBMAP"
   "<GETSUBMAP-REQUEST>"
   "GETSUBMAP-REQUEST"
   "<GETSUBMAP-RESPONSE>"
   "GETSUBMAP-RESPONSE"
  ))

