// Generated by gencpp from file car/GetLandmarks.msg
// DO NOT EDIT!


#ifndef CAR_MESSAGE_GETLANDMARKS_H
#define CAR_MESSAGE_GETLANDMARKS_H

#include <ros/service_traits.h>


#include <car/GetLandmarksRequest.h>
#include <car/GetLandmarksResponse.h>


namespace car
{

struct GetLandmarks
{

typedef GetLandmarksRequest Request;
typedef GetLandmarksResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetLandmarks
} // namespace car


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::car::GetLandmarks > {
  static const char* value()
  {
    return "06cc287e6db3b6bdd1132d19203493c2";
  }

  static const char* value(const ::car::GetLandmarks&) { return value(); }
};

template<>
struct DataType< ::car::GetLandmarks > {
  static const char* value()
  {
    return "car/GetLandmarks";
  }

  static const char* value(const ::car::GetLandmarks&) { return value(); }
};


// service_traits::MD5Sum< ::car::GetLandmarksRequest> should match 
// service_traits::MD5Sum< ::car::GetLandmarks > 
template<>
struct MD5Sum< ::car::GetLandmarksRequest>
{
  static const char* value()
  {
    return MD5Sum< ::car::GetLandmarks >::value();
  }
  static const char* value(const ::car::GetLandmarksRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::car::GetLandmarksRequest> should match 
// service_traits::DataType< ::car::GetLandmarks > 
template<>
struct DataType< ::car::GetLandmarksRequest>
{
  static const char* value()
  {
    return DataType< ::car::GetLandmarks >::value();
  }
  static const char* value(const ::car::GetLandmarksRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::car::GetLandmarksResponse> should match 
// service_traits::MD5Sum< ::car::GetLandmarks > 
template<>
struct MD5Sum< ::car::GetLandmarksResponse>
{
  static const char* value()
  {
    return MD5Sum< ::car::GetLandmarks >::value();
  }
  static const char* value(const ::car::GetLandmarksResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::car::GetLandmarksResponse> should match 
// service_traits::DataType< ::car::GetLandmarks > 
template<>
struct DataType< ::car::GetLandmarksResponse>
{
  static const char* value()
  {
    return DataType< ::car::GetLandmarks >::value();
  }
  static const char* value(const ::car::GetLandmarksResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CAR_MESSAGE_GETLANDMARKS_H
