// Generated by gencpp from file car/GetLandmarksResponse.msg
// DO NOT EDIT!


#ifndef CAR_MESSAGE_GETLANDMARKSRESPONSE_H
#define CAR_MESSAGE_GETLANDMARKSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <car/Landmark.h>

namespace car
{
template <class ContainerAllocator>
struct GetLandmarksResponse_
{
  typedef GetLandmarksResponse_<ContainerAllocator> Type;

  GetLandmarksResponse_()
    : landmarks()  {
    }
  GetLandmarksResponse_(const ContainerAllocator& _alloc)
    : landmarks(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::car::Landmark_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::car::Landmark_<ContainerAllocator> >::other >  _landmarks_type;
  _landmarks_type landmarks;




  typedef boost::shared_ptr< ::car::GetLandmarksResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::car::GetLandmarksResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetLandmarksResponse_

typedef ::car::GetLandmarksResponse_<std::allocator<void> > GetLandmarksResponse;

typedef boost::shared_ptr< ::car::GetLandmarksResponse > GetLandmarksResponsePtr;
typedef boost::shared_ptr< ::car::GetLandmarksResponse const> GetLandmarksResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::car::GetLandmarksResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::car::GetLandmarksResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace car

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'car': ['/home/marc/catkin_ws/src/car/msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::car::GetLandmarksResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::car::GetLandmarksResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::car::GetLandmarksResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::car::GetLandmarksResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::car::GetLandmarksResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::car::GetLandmarksResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::car::GetLandmarksResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c78469eba290d53592188bb13a0b4de0";
  }

  static const char* value(const ::car::GetLandmarksResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc78469eba290d535ULL;
  static const uint64_t static_value2 = 0x92188bb13a0b4de0ULL;
};

template<class ContainerAllocator>
struct DataType< ::car::GetLandmarksResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "car/GetLandmarksResponse";
  }

  static const char* value(const ::car::GetLandmarksResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::car::GetLandmarksResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Landmark[] landmarks\n\
\n\
\n\
\n\
\n\
================================================================================\n\
MSG: car/Landmark\n\
uint8 id\n\
float64 pos_x\n\
float64 pos_y\n\
float64 pos_z\n\
";
  }

  static const char* value(const ::car::GetLandmarksResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::car::GetLandmarksResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.landmarks);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetLandmarksResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::car::GetLandmarksResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::car::GetLandmarksResponse_<ContainerAllocator>& v)
  {
    s << indent << "landmarks[]" << std::endl;
    for (size_t i = 0; i < v.landmarks.size(); ++i)
    {
      s << indent << "  landmarks[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::car::Landmark_<ContainerAllocator> >::stream(s, indent + "    ", v.landmarks[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // CAR_MESSAGE_GETLANDMARKSRESPONSE_H
