# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from localization_msgs/GetSubmapRequest.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import std_msgs.msg

class GetSubmapRequest(genpy.Message):
  _md5sum = "77b19bf23675d6282563c2a11dc02863"
  _type = "localization_msgs/GetSubmapRequest"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """geometry_msgs/Point point
std_msgs/Int16 width
std_msgs/Int16 heigth

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: std_msgs/Int16
int16 data
"""
  __slots__ = ['point','width','heigth']
  _slot_types = ['geometry_msgs/Point','std_msgs/Int16','std_msgs/Int16']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       point,width,heigth

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(GetSubmapRequest, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.point is None:
        self.point = geometry_msgs.msg.Point()
      if self.width is None:
        self.width = std_msgs.msg.Int16()
      if self.heigth is None:
        self.heigth = std_msgs.msg.Int16()
    else:
      self.point = geometry_msgs.msg.Point()
      self.width = std_msgs.msg.Int16()
      self.heigth = std_msgs.msg.Int16()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3d2h().pack(_x.point.x, _x.point.y, _x.point.z, _x.width.data, _x.heigth.data))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.point is None:
        self.point = geometry_msgs.msg.Point()
      if self.width is None:
        self.width = std_msgs.msg.Int16()
      if self.heigth is None:
        self.heigth = std_msgs.msg.Int16()
      end = 0
      _x = self
      start = end
      end += 28
      (_x.point.x, _x.point.y, _x.point.z, _x.width.data, _x.heigth.data,) = _get_struct_3d2h().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3d2h().pack(_x.point.x, _x.point.y, _x.point.z, _x.width.data, _x.heigth.data))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.point is None:
        self.point = geometry_msgs.msg.Point()
      if self.width is None:
        self.width = std_msgs.msg.Int16()
      if self.heigth is None:
        self.heigth = std_msgs.msg.Int16()
      end = 0
      _x = self
      start = end
      end += 28
      (_x.point.x, _x.point.y, _x.point.z, _x.width.data, _x.heigth.data,) = _get_struct_3d2h().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3d2h = None
def _get_struct_3d2h():
    global _struct_3d2h
    if _struct_3d2h is None:
        _struct_3d2h = struct.Struct("<3d2h")
    return _struct_3d2h
# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from localization_msgs/GetSubmapResponse.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import nav_msgs.msg
import geometry_msgs.msg
import localization_msgs.msg
import sensor_msgs.msg
import genpy
import std_msgs.msg

class GetSubmapResponse(genpy.Message):
  _md5sum = "96bdf7f0bc8bb19535842d776015c489"
  _type = "localization_msgs/GetSubmapResponse"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """localization_msgs/MapDense map




================================================================================
MSG: localization_msgs/MapDense
nav_msgs/MapMetaData metadata
sensor_msgs/Image image
std_msgs/Bool valid

================================================================================
MSG: nav_msgs/MapMetaData
# This hold basic information about the characterists of the OccupancyGrid

# The time at which the map was loaded
time map_load_time
# The map resolution [m/cell]
float32 resolution
# Map width [cells]
uint32 width
# Map height [cells]
uint32 height
# The origin of the map [m, m, rad].  This is the real-world pose of the
# cell (0,0) in the map.
geometry_msgs/Pose origin
================================================================================
MSG: geometry_msgs/Pose
# A representation of pose in free space, composed of position and orientation. 
Point position
Quaternion orientation

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w

================================================================================
MSG: sensor_msgs/Image
# This message contains an uncompressed image
# (0, 0) is at top-left corner of image
#

Header header        # Header timestamp should be acquisition time of image
                     # Header frame_id should be optical frame of camera
                     # origin of frame should be optical center of cameara
                     # +x should point to the right in the image
                     # +y should point down in the image
                     # +z should point into to plane of the image
                     # If the frame_id here and the frame_id of the CameraInfo
                     # message associated with the image conflict
                     # the behavior is undefined

uint32 height         # image height, that is, number of rows
uint32 width          # image width, that is, number of columns

# The legal values for encoding are in file src/image_encodings.cpp
# If you want to standardize a new string format, join
# ros-users@lists.sourceforge.net and send an email proposing a new encoding.

string encoding       # Encoding of pixels -- channel meaning, ordering, size
                      # taken from the list of strings in include/sensor_msgs/image_encodings.h

uint8 is_bigendian    # is this data bigendian?
uint32 step           # Full row length in bytes
uint8[] data          # actual matrix data, size is (step * rows)

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id

================================================================================
MSG: std_msgs/Bool
bool data"""
  __slots__ = ['map']
  _slot_types = ['localization_msgs/MapDense']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       map

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(GetSubmapResponse, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.map is None:
        self.map = localization_msgs.msg.MapDense()
    else:
      self.map = localization_msgs.msg.MapDense()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2If2I7d3I().pack(_x.map.metadata.map_load_time.secs, _x.map.metadata.map_load_time.nsecs, _x.map.metadata.resolution, _x.map.metadata.width, _x.map.metadata.height, _x.map.metadata.origin.position.x, _x.map.metadata.origin.position.y, _x.map.metadata.origin.position.z, _x.map.metadata.origin.orientation.x, _x.map.metadata.origin.orientation.y, _x.map.metadata.origin.orientation.z, _x.map.metadata.origin.orientation.w, _x.map.image.header.seq, _x.map.image.header.stamp.secs, _x.map.image.header.stamp.nsecs))
      _x = self.map.image.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_2I().pack(_x.map.image.height, _x.map.image.width))
      _x = self.map.image.encoding
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_BI().pack(_x.map.image.is_bigendian, _x.map.image.step))
      _x = self.map.image.data
      length = len(_x)
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      buff.write(_get_struct_B().pack(self.map.valid.data))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.map is None:
        self.map = localization_msgs.msg.MapDense()
      end = 0
      _x = self
      start = end
      end += 88
      (_x.map.metadata.map_load_time.secs, _x.map.metadata.map_load_time.nsecs, _x.map.metadata.resolution, _x.map.metadata.width, _x.map.metadata.height, _x.map.metadata.origin.position.x, _x.map.metadata.origin.position.y, _x.map.metadata.origin.position.z, _x.map.metadata.origin.orientation.x, _x.map.metadata.origin.orientation.y, _x.map.metadata.origin.orientation.z, _x.map.metadata.origin.orientation.w, _x.map.image.header.seq, _x.map.image.header.stamp.secs, _x.map.image.header.stamp.nsecs,) = _get_struct_2If2I7d3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.map.image.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.map.image.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.map.image.height, _x.map.image.width,) = _get_struct_2I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.map.image.encoding = str[start:end].decode('utf-8')
      else:
        self.map.image.encoding = str[start:end]
      _x = self
      start = end
      end += 5
      (_x.map.image.is_bigendian, _x.map.image.step,) = _get_struct_BI().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.map.image.data = str[start:end]
      start = end
      end += 1
      (self.map.valid.data,) = _get_struct_B().unpack(str[start:end])
      self.map.valid.data = bool(self.map.valid.data)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2If2I7d3I().pack(_x.map.metadata.map_load_time.secs, _x.map.metadata.map_load_time.nsecs, _x.map.metadata.resolution, _x.map.metadata.width, _x.map.metadata.height, _x.map.metadata.origin.position.x, _x.map.metadata.origin.position.y, _x.map.metadata.origin.position.z, _x.map.metadata.origin.orientation.x, _x.map.metadata.origin.orientation.y, _x.map.metadata.origin.orientation.z, _x.map.metadata.origin.orientation.w, _x.map.image.header.seq, _x.map.image.header.stamp.secs, _x.map.image.header.stamp.nsecs))
      _x = self.map.image.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_2I().pack(_x.map.image.height, _x.map.image.width))
      _x = self.map.image.encoding
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_BI().pack(_x.map.image.is_bigendian, _x.map.image.step))
      _x = self.map.image.data
      length = len(_x)
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      buff.write(_get_struct_B().pack(self.map.valid.data))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.map is None:
        self.map = localization_msgs.msg.MapDense()
      end = 0
      _x = self
      start = end
      end += 88
      (_x.map.metadata.map_load_time.secs, _x.map.metadata.map_load_time.nsecs, _x.map.metadata.resolution, _x.map.metadata.width, _x.map.metadata.height, _x.map.metadata.origin.position.x, _x.map.metadata.origin.position.y, _x.map.metadata.origin.position.z, _x.map.metadata.origin.orientation.x, _x.map.metadata.origin.orientation.y, _x.map.metadata.origin.orientation.z, _x.map.metadata.origin.orientation.w, _x.map.image.header.seq, _x.map.image.header.stamp.secs, _x.map.image.header.stamp.nsecs,) = _get_struct_2If2I7d3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.map.image.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.map.image.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.map.image.height, _x.map.image.width,) = _get_struct_2I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.map.image.encoding = str[start:end].decode('utf-8')
      else:
        self.map.image.encoding = str[start:end]
      _x = self
      start = end
      end += 5
      (_x.map.image.is_bigendian, _x.map.image.step,) = _get_struct_BI().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.map.image.data = str[start:end]
      start = end
      end += 1
      (self.map.valid.data,) = _get_struct_B().unpack(str[start:end])
      self.map.valid.data = bool(self.map.valid.data)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2If2I7d3I = None
def _get_struct_2If2I7d3I():
    global _struct_2If2I7d3I
    if _struct_2If2I7d3I is None:
        _struct_2If2I7d3I = struct.Struct("<2If2I7d3I")
    return _struct_2If2I7d3I
_struct_B = None
def _get_struct_B():
    global _struct_B
    if _struct_B is None:
        _struct_B = struct.Struct("<B")
    return _struct_B
_struct_2I = None
def _get_struct_2I():
    global _struct_2I
    if _struct_2I is None:
        _struct_2I = struct.Struct("<2I")
    return _struct_2I
_struct_BI = None
def _get_struct_BI():
    global _struct_BI
    if _struct_BI is None:
        _struct_BI = struct.Struct("<BI")
    return _struct_BI
class GetSubmap(object):
  _type          = 'localization_msgs/GetSubmap'
  _md5sum = 'b8ce830ca82ddecffafefce693d0137e'
  _request_class  = GetSubmapRequest
  _response_class = GetSubmapResponse
