// Generated by gencpp from file localization_msgs/GetLandmarks.msg
// DO NOT EDIT!


#ifndef LOCALIZATION_MSGS_MESSAGE_GETLANDMARKS_H
#define LOCALIZATION_MSGS_MESSAGE_GETLANDMARKS_H

#include <ros/service_traits.h>


#include <localization_msgs/GetLandmarksRequest.h>
#include <localization_msgs/GetLandmarksResponse.h>


namespace localization_msgs
{

struct GetLandmarks
{

typedef GetLandmarksRequest Request;
typedef GetLandmarksResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetLandmarks
} // namespace localization_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::localization_msgs::GetLandmarks > {
  static const char* value()
  {
    return "06cc287e6db3b6bdd1132d19203493c2";
  }

  static const char* value(const ::localization_msgs::GetLandmarks&) { return value(); }
};

template<>
struct DataType< ::localization_msgs::GetLandmarks > {
  static const char* value()
  {
    return "localization_msgs/GetLandmarks";
  }

  static const char* value(const ::localization_msgs::GetLandmarks&) { return value(); }
};


// service_traits::MD5Sum< ::localization_msgs::GetLandmarksRequest> should match 
// service_traits::MD5Sum< ::localization_msgs::GetLandmarks > 
template<>
struct MD5Sum< ::localization_msgs::GetLandmarksRequest>
{
  static const char* value()
  {
    return MD5Sum< ::localization_msgs::GetLandmarks >::value();
  }
  static const char* value(const ::localization_msgs::GetLandmarksRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::localization_msgs::GetLandmarksRequest> should match 
// service_traits::DataType< ::localization_msgs::GetLandmarks > 
template<>
struct DataType< ::localization_msgs::GetLandmarksRequest>
{
  static const char* value()
  {
    return DataType< ::localization_msgs::GetLandmarks >::value();
  }
  static const char* value(const ::localization_msgs::GetLandmarksRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::localization_msgs::GetLandmarksResponse> should match 
// service_traits::MD5Sum< ::localization_msgs::GetLandmarks > 
template<>
struct MD5Sum< ::localization_msgs::GetLandmarksResponse>
{
  static const char* value()
  {
    return MD5Sum< ::localization_msgs::GetLandmarks >::value();
  }
  static const char* value(const ::localization_msgs::GetLandmarksResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::localization_msgs::GetLandmarksResponse> should match 
// service_traits::DataType< ::localization_msgs::GetLandmarks > 
template<>
struct DataType< ::localization_msgs::GetLandmarksResponse>
{
  static const char* value()
  {
    return DataType< ::localization_msgs::GetLandmarks >::value();
  }
  static const char* value(const ::localization_msgs::GetLandmarksResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LOCALIZATION_MSGS_MESSAGE_GETLANDMARKS_H
