// Generated by gencpp from file localization_msgs/GetSubmap.msg
// DO NOT EDIT!


#ifndef LOCALIZATION_MSGS_MESSAGE_GETSUBMAP_H
#define LOCALIZATION_MSGS_MESSAGE_GETSUBMAP_H

#include <ros/service_traits.h>


#include <localization_msgs/GetSubmapRequest.h>
#include <localization_msgs/GetSubmapResponse.h>


namespace localization_msgs
{

struct GetSubmap
{

typedef GetSubmapRequest Request;
typedef GetSubmapResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetSubmap
} // namespace localization_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::localization_msgs::GetSubmap > {
  static const char* value()
  {
    return "b8ce830ca82ddecffafefce693d0137e";
  }

  static const char* value(const ::localization_msgs::GetSubmap&) { return value(); }
};

template<>
struct DataType< ::localization_msgs::GetSubmap > {
  static const char* value()
  {
    return "localization_msgs/GetSubmap";
  }

  static const char* value(const ::localization_msgs::GetSubmap&) { return value(); }
};


// service_traits::MD5Sum< ::localization_msgs::GetSubmapRequest> should match 
// service_traits::MD5Sum< ::localization_msgs::GetSubmap > 
template<>
struct MD5Sum< ::localization_msgs::GetSubmapRequest>
{
  static const char* value()
  {
    return MD5Sum< ::localization_msgs::GetSubmap >::value();
  }
  static const char* value(const ::localization_msgs::GetSubmapRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::localization_msgs::GetSubmapRequest> should match 
// service_traits::DataType< ::localization_msgs::GetSubmap > 
template<>
struct DataType< ::localization_msgs::GetSubmapRequest>
{
  static const char* value()
  {
    return DataType< ::localization_msgs::GetSubmap >::value();
  }
  static const char* value(const ::localization_msgs::GetSubmapRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::localization_msgs::GetSubmapResponse> should match 
// service_traits::MD5Sum< ::localization_msgs::GetSubmap > 
template<>
struct MD5Sum< ::localization_msgs::GetSubmapResponse>
{
  static const char* value()
  {
    return MD5Sum< ::localization_msgs::GetSubmap >::value();
  }
  static const char* value(const ::localization_msgs::GetSubmapResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::localization_msgs::GetSubmapResponse> should match 
// service_traits::DataType< ::localization_msgs::GetSubmap > 
template<>
struct DataType< ::localization_msgs::GetSubmapResponse>
{
  static const char* value()
  {
    return DataType< ::localization_msgs::GetSubmap >::value();
  }
  static const char* value(const ::localization_msgs::GetSubmapResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LOCALIZATION_MSGS_MESSAGE_GETSUBMAP_H
