// Generated by gencpp from file controller/GetLandmarks.msg
// DO NOT EDIT!


#ifndef CONTROLLER_MESSAGE_GETLANDMARKS_H
#define CONTROLLER_MESSAGE_GETLANDMARKS_H

#include <ros/service_traits.h>


#include <controller/GetLandmarksRequest.h>
#include <controller/GetLandmarksResponse.h>


namespace controller
{

struct GetLandmarks
{

typedef GetLandmarksRequest Request;
typedef GetLandmarksResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetLandmarks
} // namespace controller


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::controller::GetLandmarks > {
  static const char* value()
  {
    return "06cc287e6db3b6bdd1132d19203493c2";
  }

  static const char* value(const ::controller::GetLandmarks&) { return value(); }
};

template<>
struct DataType< ::controller::GetLandmarks > {
  static const char* value()
  {
    return "controller/GetLandmarks";
  }

  static const char* value(const ::controller::GetLandmarks&) { return value(); }
};


// service_traits::MD5Sum< ::controller::GetLandmarksRequest> should match 
// service_traits::MD5Sum< ::controller::GetLandmarks > 
template<>
struct MD5Sum< ::controller::GetLandmarksRequest>
{
  static const char* value()
  {
    return MD5Sum< ::controller::GetLandmarks >::value();
  }
  static const char* value(const ::controller::GetLandmarksRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::controller::GetLandmarksRequest> should match 
// service_traits::DataType< ::controller::GetLandmarks > 
template<>
struct DataType< ::controller::GetLandmarksRequest>
{
  static const char* value()
  {
    return DataType< ::controller::GetLandmarks >::value();
  }
  static const char* value(const ::controller::GetLandmarksRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::controller::GetLandmarksResponse> should match 
// service_traits::MD5Sum< ::controller::GetLandmarks > 
template<>
struct MD5Sum< ::controller::GetLandmarksResponse>
{
  static const char* value()
  {
    return MD5Sum< ::controller::GetLandmarks >::value();
  }
  static const char* value(const ::controller::GetLandmarksResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::controller::GetLandmarksResponse> should match 
// service_traits::DataType< ::controller::GetLandmarks > 
template<>
struct DataType< ::controller::GetLandmarksResponse>
{
  static const char* value()
  {
    return DataType< ::controller::GetLandmarks >::value();
  }
  static const char* value(const ::controller::GetLandmarksResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CONTROLLER_MESSAGE_GETLANDMARKS_H
