// Generated by gencpp from file controller/Grid.msg
// DO NOT EDIT!


#ifndef CONTROLLER_MESSAGE_GRID_H
#define CONTROLLER_MESSAGE_GRID_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Pose2D.h>

namespace controller
{
template <class ContainerAllocator>
struct Grid_
{
  typedef Grid_<ContainerAllocator> Type;

  Grid_()
    : header()
    , ptn_mat()
    , width(0.0)
    , height(0.0)
    , resolution(0.0)
    , outdated(false)
    , origin()  {
    }
  Grid_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , ptn_mat(_alloc)
    , width(0.0)
    , height(0.0)
    , resolution(0.0)
    , outdated(false)
    , origin(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _ptn_mat_type;
  _ptn_mat_type ptn_mat;

   typedef double _width_type;
  _width_type width;

   typedef double _height_type;
  _height_type height;

   typedef double _resolution_type;
  _resolution_type resolution;

   typedef uint8_t _outdated_type;
  _outdated_type outdated;

   typedef  ::geometry_msgs::Pose2D_<ContainerAllocator>  _origin_type;
  _origin_type origin;




  typedef boost::shared_ptr< ::controller::Grid_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::controller::Grid_<ContainerAllocator> const> ConstPtr;

}; // struct Grid_

typedef ::controller::Grid_<std::allocator<void> > Grid;

typedef boost::shared_ptr< ::controller::Grid > GridPtr;
typedef boost::shared_ptr< ::controller::Grid const> GridConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::controller::Grid_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::controller::Grid_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace controller

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'controller': ['/home/marc/catkin_ws/src/controller/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::controller::Grid_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::controller::Grid_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::controller::Grid_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::controller::Grid_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::controller::Grid_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::controller::Grid_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::controller::Grid_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d1e2733602f879b37697d7b1d81ef8ce";
  }

  static const char* value(const ::controller::Grid_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd1e2733602f879b3ULL;
  static const uint64_t static_value2 = 0x7697d7b1d81ef8ceULL;
};

template<class ContainerAllocator>
struct DataType< ::controller::Grid_<ContainerAllocator> >
{
  static const char* value()
  {
    return "controller/Grid";
  }

  static const char* value(const ::controller::Grid_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::controller::Grid_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n\
float64[] ptn_mat\n\
float64 width\n\
float64 height\n\
float64 resolution\n\
bool outdated\n\
geometry_msgs/Pose2D origin\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose2D\n\
# This expresses a position and orientation on a 2D manifold.\n\
\n\
float64 x\n\
float64 y\n\
float64 theta\n\
";
  }

  static const char* value(const ::controller::Grid_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::controller::Grid_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.ptn_mat);
      stream.next(m.width);
      stream.next(m.height);
      stream.next(m.resolution);
      stream.next(m.outdated);
      stream.next(m.origin);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Grid_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::controller::Grid_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::controller::Grid_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "ptn_mat[]" << std::endl;
    for (size_t i = 0; i < v.ptn_mat.size(); ++i)
    {
      s << indent << "  ptn_mat[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.ptn_mat[i]);
    }
    s << indent << "width: ";
    Printer<double>::stream(s, indent + "  ", v.width);
    s << indent << "height: ";
    Printer<double>::stream(s, indent + "  ", v.height);
    s << indent << "resolution: ";
    Printer<double>::stream(s, indent + "  ", v.resolution);
    s << indent << "outdated: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.outdated);
    s << indent << "origin: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose2D_<ContainerAllocator> >::stream(s, indent + "  ", v.origin);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CONTROLLER_MESSAGE_GRID_H
